name: After Dependabot
on: pull_request

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Update Tapioca definitions
        run: bundle exec tapioca gem
      - name: Commit Tapioca definitions
        run: |
          if [[ $(git status | grep 'sorbet/rbi') ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add sorbet/rbi
            git commit -m '[dependabot skip] Update Tapioca definitions'
            git push
          else
            echo "Tapioca definitions have not changed"
          fi

